# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
# Optional runtime dependency: allow Ansible sanity to import this module.
try:
    import ems_grpc_pb2 as ems__grpc__pb2
    import grpc

    GRPC_GENERATED_VERSION = "1.84.0"
    GRPC_VERSION = grpc.__version__
    _version_not_supported = False

    try:
        from grpc._utilities import first_version_is_lower

        _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
    except ImportError:
        _version_not_supported = True

    if _version_not_supported:
        raise RuntimeError(
            f"The grpc package installed is at version {GRPC_VERSION},"
            + " but the generated code in ems_grpc_pb2_grpc.py depends on"
            + f" grpcio>={GRPC_GENERATED_VERSION}."
            + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
            + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.",
        )

    class gRPCConfigOperStub:
        """Missing associated documentation comment in .proto file."""

        def __init__(self, channel):
            """Constructor.

            Args:
                channel: A grpc.Channel.
            """
            self.GetConfig = channel.unary_stream(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetConfig",
                request_serializer=ems__grpc__pb2.ConfigGetArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ConfigGetReply.FromString,
                _registered_method=True,
            )
            self.MergeConfig = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/MergeConfig",
                request_serializer=ems__grpc__pb2.ConfigArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ConfigReply.FromString,
                _registered_method=True,
            )
            self.DeleteConfig = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/DeleteConfig",
                request_serializer=ems__grpc__pb2.ConfigArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ConfigReply.FromString,
                _registered_method=True,
            )
            self.ReplaceConfig = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ReplaceConfig",
                request_serializer=ems__grpc__pb2.ConfigArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ConfigReply.FromString,
                _registered_method=True,
            )
            self.CliConfig = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CliConfig",
                request_serializer=ems__grpc__pb2.CliConfigArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.CliConfigReply.FromString,
                _registered_method=True,
            )
            self.CommitReplace = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitReplace",
                request_serializer=ems__grpc__pb2.CommitReplaceArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.CommitReplaceReply.FromString,
                _registered_method=True,
            )
            self.CommitConfig = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitConfig",
                request_serializer=ems__grpc__pb2.CommitArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.CommitReply.FromString,
                _registered_method=True,
            )
            self.ConfigDiscardChanges = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ConfigDiscardChanges",
                request_serializer=ems__grpc__pb2.DiscardChangesArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.DiscardChangesReply.FromString,
                _registered_method=True,
            )
            self.GetOper = channel.unary_stream(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetOper",
                request_serializer=ems__grpc__pb2.GetOperArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.GetOperReply.FromString,
                _registered_method=True,
            )
            self.CreateSubs = channel.unary_stream(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CreateSubs",
                request_serializer=ems__grpc__pb2.CreateSubsArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.CreateSubsReply.FromString,
                _registered_method=True,
            )

    class gRPCConfigOperServicer:
        """Missing associated documentation comment in .proto file."""

        def GetConfig(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def MergeConfig(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def DeleteConfig(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def ReplaceConfig(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def CliConfig(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def CommitReplace(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def CommitConfig(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def ConfigDiscardChanges(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def GetOper(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def CreateSubs(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

    def add_gRPCConfigOperServicer_to_server(servicer, server):
        rpc_method_handlers = {
            "GetConfig": grpc.unary_stream_rpc_method_handler(
                servicer.GetConfig,
                request_deserializer=ems__grpc__pb2.ConfigGetArgs.FromString,
                response_serializer=ems__grpc__pb2.ConfigGetReply.SerializeToString,
            ),
            "MergeConfig": grpc.unary_unary_rpc_method_handler(
                servicer.MergeConfig,
                request_deserializer=ems__grpc__pb2.ConfigArgs.FromString,
                response_serializer=ems__grpc__pb2.ConfigReply.SerializeToString,
            ),
            "DeleteConfig": grpc.unary_unary_rpc_method_handler(
                servicer.DeleteConfig,
                request_deserializer=ems__grpc__pb2.ConfigArgs.FromString,
                response_serializer=ems__grpc__pb2.ConfigReply.SerializeToString,
            ),
            "ReplaceConfig": grpc.unary_unary_rpc_method_handler(
                servicer.ReplaceConfig,
                request_deserializer=ems__grpc__pb2.ConfigArgs.FromString,
                response_serializer=ems__grpc__pb2.ConfigReply.SerializeToString,
            ),
            "CliConfig": grpc.unary_unary_rpc_method_handler(
                servicer.CliConfig,
                request_deserializer=ems__grpc__pb2.CliConfigArgs.FromString,
                response_serializer=ems__grpc__pb2.CliConfigReply.SerializeToString,
            ),
            "CommitReplace": grpc.unary_unary_rpc_method_handler(
                servicer.CommitReplace,
                request_deserializer=ems__grpc__pb2.CommitReplaceArgs.FromString,
                response_serializer=ems__grpc__pb2.CommitReplaceReply.SerializeToString,
            ),
            "CommitConfig": grpc.unary_unary_rpc_method_handler(
                servicer.CommitConfig,
                request_deserializer=ems__grpc__pb2.CommitArgs.FromString,
                response_serializer=ems__grpc__pb2.CommitReply.SerializeToString,
            ),
            "ConfigDiscardChanges": grpc.unary_unary_rpc_method_handler(
                servicer.ConfigDiscardChanges,
                request_deserializer=ems__grpc__pb2.DiscardChangesArgs.FromString,
                response_serializer=ems__grpc__pb2.DiscardChangesReply.SerializeToString,
            ),
            "GetOper": grpc.unary_stream_rpc_method_handler(
                servicer.GetOper,
                request_deserializer=ems__grpc__pb2.GetOperArgs.FromString,
                response_serializer=ems__grpc__pb2.GetOperReply.SerializeToString,
            ),
            "CreateSubs": grpc.unary_stream_rpc_method_handler(
                servicer.CreateSubs,
                request_deserializer=ems__grpc__pb2.CreateSubsArgs.FromString,
                response_serializer=ems__grpc__pb2.CreateSubsReply.SerializeToString,
            ),
        }
        generic_handler = grpc.method_handlers_generic_handler(
            "IOSXRExtensibleManagabilityService.gRPCConfigOper",
            rpc_method_handlers,
        )
        server.add_generic_rpc_handlers((generic_handler,))
        server.add_registered_method_handlers(
            "IOSXRExtensibleManagabilityService.gRPCConfigOper",
            rpc_method_handlers,
        )

    # This class is part of an EXPERIMENTAL API.
    class gRPCConfigOper:
        """Missing associated documentation comment in .proto file."""

        @staticmethod
        def GetConfig(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_stream(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetConfig",
                ems__grpc__pb2.ConfigGetArgs.SerializeToString,
                ems__grpc__pb2.ConfigGetReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

        @staticmethod
        def MergeConfig(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/MergeConfig",
                ems__grpc__pb2.ConfigArgs.SerializeToString,
                ems__grpc__pb2.ConfigReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

        @staticmethod
        def DeleteConfig(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/DeleteConfig",
                ems__grpc__pb2.ConfigArgs.SerializeToString,
                ems__grpc__pb2.ConfigReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

        @staticmethod
        def ReplaceConfig(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ReplaceConfig",
                ems__grpc__pb2.ConfigArgs.SerializeToString,
                ems__grpc__pb2.ConfigReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

        @staticmethod
        def CliConfig(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CliConfig",
                ems__grpc__pb2.CliConfigArgs.SerializeToString,
                ems__grpc__pb2.CliConfigReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

        @staticmethod
        def CommitReplace(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitReplace",
                ems__grpc__pb2.CommitReplaceArgs.SerializeToString,
                ems__grpc__pb2.CommitReplaceReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

        @staticmethod
        def CommitConfig(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitConfig",
                ems__grpc__pb2.CommitArgs.SerializeToString,
                ems__grpc__pb2.CommitReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

        @staticmethod
        def ConfigDiscardChanges(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ConfigDiscardChanges",
                ems__grpc__pb2.DiscardChangesArgs.SerializeToString,
                ems__grpc__pb2.DiscardChangesReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

        @staticmethod
        def GetOper(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_stream(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetOper",
                ems__grpc__pb2.GetOperArgs.SerializeToString,
                ems__grpc__pb2.GetOperReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

        @staticmethod
        def CreateSubs(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_stream(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CreateSubs",
                ems__grpc__pb2.CreateSubsArgs.SerializeToString,
                ems__grpc__pb2.CreateSubsReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

    class gRPCExecStub:
        """Missing associated documentation comment in .proto file."""

        def __init__(self, channel):
            """Constructor.

            Args:
                channel: A grpc.Channel.
            """
            self.ShowCmdTextOutput = channel.unary_stream(
                "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdTextOutput",
                request_serializer=ems__grpc__pb2.ShowCmdArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ShowCmdTextReply.FromString,
                _registered_method=True,
            )
            self.ShowCmdJSONOutput = channel.unary_stream(
                "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdJSONOutput",
                request_serializer=ems__grpc__pb2.ShowCmdArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ShowCmdJSONReply.FromString,
                _registered_method=True,
            )

    class gRPCExecServicer:
        """Missing associated documentation comment in .proto file."""

        def ShowCmdTextOutput(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def ShowCmdJSONOutput(self, request, context):
            """Missing associated documentation comment in .proto file."""
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

    def add_gRPCExecServicer_to_server(servicer, server):
        rpc_method_handlers = {
            "ShowCmdTextOutput": grpc.unary_stream_rpc_method_handler(
                servicer.ShowCmdTextOutput,
                request_deserializer=ems__grpc__pb2.ShowCmdArgs.FromString,
                response_serializer=ems__grpc__pb2.ShowCmdTextReply.SerializeToString,
            ),
            "ShowCmdJSONOutput": grpc.unary_stream_rpc_method_handler(
                servicer.ShowCmdJSONOutput,
                request_deserializer=ems__grpc__pb2.ShowCmdArgs.FromString,
                response_serializer=ems__grpc__pb2.ShowCmdJSONReply.SerializeToString,
            ),
        }
        generic_handler = grpc.method_handlers_generic_handler(
            "IOSXRExtensibleManagabilityService.gRPCExec",
            rpc_method_handlers,
        )
        server.add_generic_rpc_handlers((generic_handler,))
        server.add_registered_method_handlers(
            "IOSXRExtensibleManagabilityService.gRPCExec",
            rpc_method_handlers,
        )

    # This class is part of an EXPERIMENTAL API.
    class gRPCExec:
        """Missing associated documentation comment in .proto file."""

        @staticmethod
        def ShowCmdTextOutput(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_stream(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdTextOutput",
                ems__grpc__pb2.ShowCmdArgs.SerializeToString,
                ems__grpc__pb2.ShowCmdTextReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

        @staticmethod
        def ShowCmdJSONOutput(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_stream(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdJSONOutput",
                ems__grpc__pb2.ShowCmdArgs.SerializeToString,
                ems__grpc__pb2.ShowCmdJSONReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
                _registered_method=True,
            )

except ImportError:
    pass
